### ISSUE TITLE
Inserting new points - replacing old points

### ISSUE THREAD

**Issue by djdan7** [hugoledoux/startinpy#16]
Hello!
Is it possible to add a new parameter in the function "insert_one_pt()", called e.g. "replace", so when "replace=True", then if there is a point at the same location (based on [startinpy.DT.snap_tolerance()], then the point IS REPLACED?

Thank you for response :)

Greetings!

**Comment by hugoledoux** [comment]
in v0.10 it is not, but I have added this to the upcoming version.

It's called xy-duplicate handling, and if you download and install the 'develop' branch and install yourself the bindings (should take you 10min max), then this is work. Or you wait perhaps 4-5 weeks and v0.11 will be released.

The docs for v0.11 is online already: https://startinpy.readthedocs.io/en/develop/api.html and see that function: https://startinpy.readthedocs.io/en/develop/api.html#startinpy.DT.duplicates_handling

If you test it, I'm interested in feedback and whether those functions are useful for you.

**Comment by djdan7** [comment]
Thank you. I will try to compile it in free time. 

I see that there will be a lot of other new features in v0.11. Great!!! :D

Have you thought about adding one more functionality - group deletion of points? I would see 3 options here:
1. A circle with center X,Y and radius r
2. A rectangle with center X,Y and dimensions a, b
3. A rectangle with center X,Y, dimensions a, b and direction of rotation alpha

Currently, in my application I have to delete points and insert new so I wrote a small script for this (option 3 above) based on your startinpy library and numpy vectorization. But if there are more than let's say 1.000.000 points in the database, my code starts to slow down due to copying points database.

**Comment by hugoledoux** [comment]
What do you mean by "copying points database"? Is this something you perform or are you referring to an operation of startinpy? If you remove points, there is no copying the space allocated for that vertex is just assigned as deleted, nothing is removed from the array of vertices.

**Comment by hugoledoux** [comment]
okay I'll see, thanks, this is useful.

2D area is there in the code but not exposed, I can expose it.
volume I can add in 5min.

**Comment by djdan7** [comment]
Great, thank you for making this library, it is very helpful and really fast! :D

**Comment by djdan7** [comment]
@hugoledoux can you guide me, how exactly I can compile the "develop" version 0.11? I have downloaded .ZIP file from "develop" github branch, installed latest RUST and maturin. And now I am not sure how to make next steps :/

**Comment by djdan7** [comment]
I have managed to compile v0.11.0 beta version. Duplicates handling works, but I have one more suggestion - it would be great if also X and Y coordinates would be changed when duplicates_handling set to "Last" (or something like "LastXYZ"). Is it possible? Greetings!!

**Comment by hugoledoux** [comment]
Great. 

I don't understand what you mean here I'm afraid. xy cannot be changed/modified, or a new point is inserted somewhere else and that's not a duplicate.

**Comment by djdan7** [comment]
I will describe a situation in which such a function could be used:

snap_tolerance is set to a high level (e.g. 0.20m) to save memory and collect data over a larger area. Fresh measurements have just appeared and I would like to update them in the database. For example, I would like to replace the old point [10, 10, 10] with [10.1, 10.1, 9]. But at the moment there will be point [10, 10, 9] in the database. This is ok for some situations (especially when snap_tolerance is set at a low level, e.g. 1 cm), but in terrain with a steep slopes it causes an increase in errors, especially in volume calculations, about which we wrote before. If there was a function that also replaced the XY coordinates, the measurement accuracy would be maintained. I understand that changing the XY coordinates would involve recalculating the triangulation, but if the user has such a need, he agrees to it. At this point, you must first find a close point to replace, then remove it and then add a new fresh point. If these steps could be simplified and a feature like this added, that would be great. 

Have I described the situation sufficiently?

**Comment by hugoledoux** [comment]
okay I now understand.

Indeed moving points can change the topology of the triangulation, and in some cases the triangles would have to be recomputed. 

I don't see how to implement this in startinpy elegantly, sorry. 

I suggest you implement it yourself: if that happens you can collect all the points wiht `dt.points` and insert them again.

**Comment by hugoledoux** [comment]
okay I added area + volume: 6547985dcafe376be8256fff68c933a8667e281a + 32b87d0c8981df4395b32518b6c171da192c89fa

area is both:
1. 2d (projected to the xy-plane)
2. 3d (real area in 3D)

volume is wrt to a z-plane, and you get the signed volume, so if you have the z-plane above your triangle you'll get a negative value. I am not sure I use the same formula as you, the '@' is not an operator I know and you calculate only to the average of the 3 z-values, I perform the exact volume computation.
