### ISSUE TITLE
Multiprocessing - TypeError: cannot pickle 'builtins.DT' object

### ISSUE THREAD

**Issue by djdan7** [hugoledoux/startinpy#17]
Hello!
I get "TypeError: cannot pickle 'builtins.DT' object" when I want to use "self.dt = startinpy.DT()" on another process

You can reproduce it by running this code:

```
import startinpy
from multiprocessing import Process


class WorkCl:
    def __init__(self):
        self.dtm = DTM()  # PROCESS
        self.dtm.start()


class DTM(Process):
    def __init__(self):
        Process.__init__(self)
        self.dt = startinpy.DT()


wcl = WorkCl()
```

Do you know how I can workaround this?

**Comment by hugoledoux** [comment]
duplicates of #10

it's on my side, not yours. I might fix this eventually.
