### ISSUE TITLE
v0.11.0 beta: OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by djdan7** [hugoledoux/startinpy#19]
When I use int32 or uint32 in attributes (for example: `dt.set_attributes_schema(np.dtype([('intensity', np.uint32)]))` and want to print the attributes using `dt.attributes[1:]` I get:  `OverflowError: Python int too large to convert to C long`. 

floats and 64bit integers works ok

**Comment by hugoledoux** [comment]
this means indeed you have values of intensity that are larger than the max value for int32?

this would mean (2^32)/2 = 2.147.483.648, I doubt this is the case?

**Comment by hugoledoux** [comment]
I'll close this for now since I haven't heard from you, reopen if still an issue
