### ISSUE TITLE
Reference or clarification for flipping.

### ISSUE THREAD

**Issue by kylemann16** [hugoledoux/startinpy#28]
> The algorithm is based on flips
> The ears are filled by flipping

Found in [howitworks.md lines 13 and 17](https://github.com/hugoledoux/startinpy/blob/master/docs/howitworks.md?plain=1#L13). Is this referring to the `Lawson Flip Algorithm`? If so, this should be referenced inline. 

I see you referencing it in [ref.bib:23](https://github.com/hugoledoux/startinpy/blob/master/paper/ref.bib#L23), but not for this section.

If this is not a reference to Lawson, then an explanation/link to an explanation should probably be included.

**Comment by hugoledoux** [comment]
It's indeed Lawson72: https://doi.org/10.1016/0012-365X(72)90093-3

Fixed it, cheers
